nodeLinker: node-modules

packageExtensions:
  "@algolia/autocomplete-shared@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
      algoliasearch:
        optional: true
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependenciesMeta:
      search-insights:
        optional: true
  "@algolia/autocomplete-preset-algolia@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
