export const REQUIRED_CHALLENGE_LENGTH = 36;
export const CERTIFICATE_NAME_MIN_LENGTH = 5;
export const CERTIFICATE_NAME_MAX_LENGTH = 100;
export const SUBUNIT_NAME_MIN_LENGTH = 5;
export const SUBUNIT_NAME_MAX_LENGTH = 256;
export const PERMISSION_DESCRIPTION_MIN_LENGTH = 5;
export const PERMISSION_DESCRIPTION_MAX_LENGTH = 256;
