import { defineCommand } from 'citty';

// Mirrors the subCommands of src/cli/index.ts, in the same order — completion-tree.test.ts
// fails if the two drift apart.
export const COMMAND_TREE: Record<string, string[]> = {
  setup: [],
  config: ['set', 'show', 'reset'],
  auth: ['challenge', 'login', 'login-external', 'status', 'logout', 'refresh', 'whoami', 'revoke-self-token'],
  session: ['open', 'close', 'status', 'active', 'revoke', 'list', 'invoices', 'invoice', 'failed', 'upo'],
  invoice: ['send', 'get', 'query', 'build', 'pdf', 'validate', 'export', 'export-status', 'export-incremental'],
  permission: ['grant', 'revoke', 'search', 'status', 'attachment-status'],
  token: ['generate', 'list', 'get', 'revoke'],
  cert: ['generate', 'enrollment-data', 'enroll', 'status', 'retrieve', 'list', 'revoke', 'limits'],
  qr: ['invoice', 'certificate', 'url'],
  lighthouse: ['status', 'messages'],
  limits: ['context', 'subject', 'rate'],
  'collective-identifier': ['generate', 'list', 'by-ksef', 'invoices'],
  peppol: ['providers'],
  'test-data': [
    'create-subject', 'remove-subject', 'create-person', 'remove-person',
    'grant-permissions', 'revoke-permissions', 'enable-attachment', 'disable-attachment',
    'change-session-limits', 'restore-session-limits', 'change-cert-limits', 'restore-cert-limits',
    'set-rate-limits', 'restore-rate-limits', 'set-production-rate-limits',
    'update-certificate',
    'block-context', 'unblock-context',
  ],
  offline: ['generate', 'list', 'status', 'submit', 'correct', 'delete'],
  doctor: [],
  completion: ['bash', 'zsh', 'fish'],
};

const TOP_COMMANDS = Object.keys(COMMAND_TREE).join(' ');

function generateBash(): string {
  const cases = Object.entries(COMMAND_TREE)
    .filter(([, subs]) => subs.length > 0)
    .map(([cmd, subs]) => `      ${cmd}) COMPREPLY=($(compgen -W "${subs.join(' ')}" -- "$cur")) ;;`)
    .join('\n');

  return `# ksef bash completion — generated by ksef completion bash
_ksef_completions() {
  local cur prev commands
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${TOP_COMMANDS}"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    return 0
  fi

  case "$prev" in
${cases}
  esac
}
complete -F _ksef_completions ksef
`;
}

function generateZsh(): string {
  const cases = Object.entries(COMMAND_TREE)
    .filter(([, subs]) => subs.length > 0)
    .map(([cmd, subs]) => `    ${cmd}) compadd ${subs.join(' ')} ;;`)
    .join('\n');

  return `#compdef ksef
# ksef zsh completion — generated by ksef completion zsh
_ksef() {
  local -a commands
  commands=(${Object.entries(COMMAND_TREE).map(([cmd]) => `'${cmd}:${cmd} commands'`).join(' ')})

  _arguments '1:command:->cmds' '*::arg:->args'

  case "$state" in
    cmds)
      _describe 'command' commands
      ;;
    args)
      case "$words[1]" in
${cases}
      esac
      ;;
  esac
}
_ksef "$@"
`;
}

function generateFish(): string {
  const lines = [`# ksef fish completion — generated by ksef completion fish`];
  lines.push(`complete -c ksef -f`);

  for (const [cmd, subs] of Object.entries(COMMAND_TREE)) {
    lines.push(`complete -c ksef -n '__fish_use_subcommand' -a '${cmd}' -d '${cmd} commands'`);
    for (const sub of subs) {
      lines.push(`complete -c ksef -n '__fish_seen_subcommand_from ${cmd}' -a '${sub}'`);
    }
  }

  return lines.join('\n') + '\n';
}

const bash = defineCommand({
  meta: { name: 'bash', description: 'Generate bash completion script' },
  run() {
    console.log(generateBash());
  },
});

const zsh = defineCommand({
  meta: { name: 'zsh', description: 'Generate zsh completion script' },
  run() {
    console.log(generateZsh());
  },
});

const fish = defineCommand({
  meta: { name: 'fish', description: 'Generate fish completion script' },
  run() {
    console.log(generateFish());
  },
});

export const completionCommand = defineCommand({
  meta: { name: 'completion', description: 'Generate shell completion scripts' },
  subCommands: { bash, zsh, fish },
});
